# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import os
import sys
import time
import re
import threading
from pathlib import Path
from typing import Optional
from .utils import safe_print, C, log
from .tools import ExecutionRegistry
from .agent import OpenRouterAgent


cmd_registry = ExecutionRegistry()

@cmd_registry.register("status", "レート制限状態を表示")
def cmd_status(agent: OpenRouterAgent, args: str):
    agent.print_status()

@cmd_registry.register("clear", "会話履歴をリセット")
def cmd_clear(agent: OpenRouterAgent, args: str):
    agent.clear_history()
    safe_print("会話履歴をクリアしました。")

# Gemma 4 向け推論指示（system_prompt への注入・除去で切り替える）
_THINKING_INSTRUCTION = (
    "行動・回答する前に必ず<thinking>タグ内で問題を段階的に深く推論・分析し、"
    "複数の選択肢を検討してから最善策を実行してください。"
)

@cmd_registry.register("think", "推論モードの確認・切替 (/think on|off)")
def cmd_think(agent: OpenRouterAgent, args: str):
    arg = args.strip().lower()
    if arg == "on":
        agent.set_thinking(True)
        # system_prompt に推論指示がなければ末尾に追加
        if agent.system_prompt and _THINKING_INSTRUCTION not in agent.system_prompt:
            agent.system_prompt = agent.system_prompt.rstrip() + "\n" + _THINKING_INSTRUCTION
        safe_print(C.green("  推論モード: ON  — <thinking> 指示をプロンプトに注入しました。"))
    elif arg == "off":
        agent.set_thinking(False)
        # system_prompt から推論指示を除去
        if agent.system_prompt:
            agent.system_prompt = agent.system_prompt.replace(
                "\n" + _THINKING_INSTRUCTION, ""
            ).replace(_THINKING_INSTRUCTION, "")
        safe_print(C.yellow("  推論モード: OFF — <thinking> 指示をプロンプトから除去しました。"))
    else:
        state = "ON" if agent.thinking_enabled else "OFF"
        injected = agent.system_prompt and _THINKING_INSTRUCTION in (agent.system_prompt or "")
        prompt_mark = C.green("注入済み") if injected else C.gray("未注入")
        safe_print(f"  推論モード: {C.green('ON') if agent.thinking_enabled else C.yellow('OFF')}"
                   f"  (プロンプト指示: {prompt_mark})")
        safe_print(C.gray("  切替: /think on  または  /think off"))

@cmd_registry.register("model", "モデルの確認・変更 (/model → ライブ選択  /model <名前> → 直接指定)")
def cmd_model(agent: OpenRouterAgent, args: str):
    current = agent._config.model
    arg = args.strip()

    if not arg:
        # 引数なし → 起動時と同じライブセレクタを起動
        from .config import select_model_interactively
        new_model, new_ctx = select_model_interactively(agent._config.api_keys[0], current)
        if new_model != current:
            agent._config.model = new_model
            agent._config.context_length = new_ctx
            agent._update_compaction_threshold()
            agent.clear_history()
            safe_print(C.green(f"  ✓ モデルを変更しました: {new_model}"))
            safe_print(C.gray("  会話履歴をリセットしました。"))
        else:
            safe_print(C.gray(f"  モデルは変更されませんでした: {current}"))
        return

    # 引数あり → モデル名を直接指定
    agent._config.model = arg
    agent.clear_history()
    safe_print(C.green(f"  ✓ モデルを変更しました: {arg}"))
    safe_print(C.gray("  会話履歴をリセットしました。"))

@cmd_registry.register("cd", "作業フォルダの確認・変更 (/cd <パス>)")
def cmd_cd(agent: OpenRouterAgent, args: str):
    if not args:
        safe_print(f"  現在の作業フォルダ: {agent.cwd}")
        return
    new_path = args.strip().strip('"').strip("'")
    expanded = str(Path(new_path).expanduser().resolve())
    if Path(expanded).exists():
        agent.set_cwd(expanded)
    else:
        safe_print(f"  フォルダが見つかりません: {expanded}")

@cmd_registry.register("task", "タスクの確認・開始 (/task <ゴール> | end)")
def cmd_task(agent: OpenRouterAgent, args: str):
    if args.lower() == "end":
        agent.end_task()
        safe_print("  タスクを終了しました。")
    elif args:
        agent.start_task(args)
        safe_print(f"  タスク開始: {args}")
    else:
        if agent._task_goal:
            safe_print(f"  現在のタスク: {agent._task_goal}")
        else:
            safe_print("  タスクなし（/task <ゴール> で開始）")

@cmd_registry.register("help", "コマンド一覧を表示")
def cmd_help(agent: OpenRouterAgent, args: str):
    safe_print(cmd_registry.help_text())

